# Generated by Django 3.2.23 on 2023-11-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
