# Generated by Django 3.2.23 on 2023-11-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarsapp', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(upload_to='Product_images/'),
        ),
    ]
