# Generated by Django 3.2.23 on 2023-11-25 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycarsapp', '0008_auto_20231123_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('MSA', 'MOMBASA'), ('NRB', 'NAIROBI'), ('BSA', 'BUSIA'), ('NKR', 'NAKURU'), ('BGM', 'BUNGOMA'), ('KMG', 'KAKAMEGA'), ('ELD', 'ELDORET'), ('TRK', 'TURKANA'), ('KBU', 'KIAMBU'), ('KTI', 'KITUI')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('MSA', 'MOMBASA'), ('NRB', 'NAIROBI'), ('BSA', 'BUSIA'), ('NKR', 'NAKURU'), ('BGM', 'BUNGOMA'), ('KMG', 'KAKAMEGA'), ('ELD', 'ELDORET'), ('TRK', 'TURKANA'), ('KBU', 'KIAMBU'), ('KTI', 'KITUI')], max_length=100)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycarsapp.customer')),
            ],
        ),
    ]
